#!/usr/bin/expect

set DEBUG 1
log_file performed.txt

set timeout 20
set user settlementUser
set fp [open "current.pess" r]
set currentpess [read $fp]
set fq [open "new.pess" r]
set newpess [read $fq]
set fr [open "new.pess" r]
set newpess2 [read $fr]

spawn sudo -u <Application Command to change pass>
expect "Username:"
send "$user\r"

expect "Password:" 
send "$currentpess"

expect "New password:" 
send "$newpess"

expect "Repeat new password:" 
send "$newpess2"

expect "$"
