#!/usr/bin/expect
# info: Expect script 
# To push files on multiple servers via SSH
# 
#
#
set timeout 5
set prompt "(%|#|\\$|%\]) $"
set fid [open ./HOSTS r]
set contents [read -nonewline $fid]
close $fid
stty echo
send_user "\nUsername for SSH connection: "
expect_user -re "(.*)\n" {set sshname $expect_out(1,string)}
send_user "\nPassword for SSH user: "
stty -echo
expect_user -re "(.*)\n" {set sshpassword $expect_out(1,string)}
stty echo
foreach host [split $contents "\n"] {
spawn scp -P 3345 -o StrictHostKeyChecking=no FILE $sshname@$host:/home/USER/
expect {
  "assword:" { send -- "$sshpassword\r"
  }
  "you sure you want to continue connecting" {
  send -- "yes\r"
  expect "assword:"
  send -- "$sshpassword\r"
  }
}
expect -re "$prompt"
send -- "echo Done!\r"
}
